Ricardo Barrios-200124504
sjdonado/assessment-1-backend-un-202130 pull request #25
Opened 2021-08-17 19:35 UTC by Rbarriosbm

first commit

2021-08-18 06:11 UTC, sjdonado requested changes
Realiza el cambio sugerido y sube cambios (push a la misma rama)

2021-08-18 06:11 UTC, sjdonado commented on .github/workflows/main.yml
> +          N_VALUE: 9
```suggestion
          N_VALUE: 12
```

2021-08-22 19:45 UTC, Rbarriosbm commented
add + new N_VALUE parameter

2021-08-22 20:04 UTC, sjdonado approved these changes
Done!

2021-08-22 20:04 UTC, closed without merging