Mi primer Commit Envio de todo los cambios
sjdonado/assessment-1-backend-un-202130 pull request #30
Opened 2021-08-18 00:33 UTC by elcontreras

**Código del Estudiante:** _200110747_

2021-08-18 06:19 UTC, sjdonado requested changes
Realiza el cambio sugerido y sube cambios (push a la misma rama)

2021-08-18 06:19 UTC, sjdonado commented on .github/workflows/main.yml
> +          N_INDEX: 9
```suggestion
          N_INDEX: 12
```

2021-08-19 17:46 UTC, elcontreras reviewed
Codigo: 200110747

2021-08-19 17:46 UTC, elcontreras commented on .github/workflows/main.yml
> +          N_INDEX: 9
Enviado por Commit

2021-08-20 14:58 UTC, sjdonado approved these changes
Done!

2021-08-20 14:58 UTC, closed without merging