PR: 200055635
sjdonado/assessment-1-backend-un-202130 pull request #37
Opened 2021-08-18 04:43 UTC by estnelsoncaraballo

2021-08-18 06:30 UTC, sjdonado requested changes
Realiza el cambio sugerido y sube cambios (push a la misma rama)

2021-08-18 06:30 UTC, sjdonado commented on .github/workflows/main.yml
> +            N_INPUT: 9
```suggestion
            N_INPUT: 12
```

2021-08-19 18:02 UTC, estnelsoncaraballo commented on .github/workflows/main.yml
> +            N_INPUT: 9
ya realice el commit

2021-08-20 14:56 UTC, sjdonado approved these changes
Done!

2021-08-20 14:56 UTC, closed without merging