Primer Parcial - Ricardo Alvarez Correa
sjdonado/assessment-1-backend-un-202130 pull request #6
Opened 2021-08-16 00:25 UTC by rialco

Codigo : 200100445

2021-08-18 05:38 UTC, sjdonado requested changes
Realiza el cambio sugerido y sube cambios (push a la misma rama)

2021-08-18 05:38 UTC, sjdonado commented on .github/workflows/main.yml
> +          N_INDEX: 9
```suggestion
          N_INDEX: 12
```

2021-08-18 20:08 UTC, rialco commented on .github/workflows/main.yml
> +          N_INDEX: 9
Realizado

2021-08-19 12:05 UTC, sjdonado approved these changes
Done!

2021-08-19 12:06 UTC, closed without merging